# Practice for Filtering with SQL

Import the germane libraries and connect to the database.

In [1]:
# Run this code

import pandas as pd
import sqlite3

conn = sqlite3.connect('data.sqlite')
pd.read_sql("""
SELECT *
  FROM employees;
""", conn)

,employeeNumber,lastName,firstName,extension,email,officeCode,reportsTo,jobTitle
0,1002,Murphy,Diane,x5800,dmurphy@classicmodelcars.com,1,,President
1,1056,Patterson,Mary,x4611,mpatterso@classicmodelcars.com,1,1002,VP Sales
2,1076,Firrelli,Jeff,x9273,jfirrelli@classicmodelcars.com,1,1002,VP Marketing
3,1088,Patterson,William,x4871,wpatterson@classicmodelcars.com,6,1056,Sales Manager (APAC)
4,1102,Bondur,Gerard,x5408,gbondur@classicmodelcars.com,4,1056,Sale Manager (EMEA)
5,1143,Bow,Anthony,x5428,abow@classicmodelcars.com,1,1056,Sales Manager (NA)
6,1165,Jennings,Leslie,x3291,ljennings@classicmodelcars.com,1,1143,Sales Rep
7,1166,Thompson,Leslie,x4065,lthompson@classicmodelcars.com,1,1143,Sales Rep
8,1188,Firrelli,Julie,x2173,jfirrelli@classicmodelcars.com,2,1143,Sales Rep
9,1216,Patterson,Steve,x4334,spatterson@classicmodelcars.com,2,1143,Sales Rep
10,1286,Tseng,Foon Yue,x2248,ftseng@classicmodelcars.com,3,1143,Sales Rep
11,1323,Vanauf,George,x4102,gvanauf@classicmodelcars.com,3,1143,Sales Rep
12,1337,Bondur,Loui,x6493,lbondur@classicmodelcars.com,4,1102,Sales Rep
13,1370,Hernandez,Gerard,x2028,ghernande@classicmodelcars.com,4,1102,Sales Rep
14,1401,Castillo,Pamela,x2759,pcastillo@classicmodelcars.com,4,1102,Sales Rep
15,1501,Bott,Larry,x2311,lbott@classicmodelcars.com,7,1102,Sales Rep
16,1504,Jones,Barry,x102,bjones@classicmodelcars.com,7,1102,Sales Rep
17,1611,Fixter,Andy,x101,afixter@classicmodelcars.com,6,1088,Sales Rep
18,1612,Marsh,Peter,x102,pmarsh@classicmodelcars.com,6,1088,Sales Rep
19,1619,King,Tom,x103,tking@classicmodelcars.com,6,1088,Sales Rep
20,1621,Nishi,Mami,x101,mnishi@classicmodelcars.com,5,1056,Sales Rep
21,1625,Kato,Yoshimi,x102,ykato@classicmodelcars.com,5,1621,Sales Rep
22,1702,Gerard,Martin,x2312,mgerard@classicmodelcars.com,4,1102,Sales Rep

1. Select all of the employees with first name "Leslie"

In [6]:
# Fist name Leslie

# pd.read_sql("""
# SELECT *
#  FROM cats
# WHERE age >= 5;
# """, conn)

pd.read_sql( """ 

SELECT * FROM employees WHERE firstName = "Leslie";

""", conn )

,employeeNumber,lastName,firstName,extension,email,officeCode,reportsTo,jobTitle
0,1165,Jennings,Leslie,x3291,ljennings@classicmodelcars.com,1,1143,Sales Rep
1,1166,Thompson,Leslie,x4065,lthompson@classicmodelcars.com,1,1143,Sales Rep

2. For the employees named Leslie, give the first name, last name, and job title.

In [8]:
# First name Leslie, with last name and title

pd.read_sql( """ 

SELECT firstName, lastName, jobTitle FROM employees WHERE firstName = "Leslie"; 

""",conn )

  firstName  lastName   jobTitle
0    Leslie  Jennings  Sales Rep
1    Leslie  Thompson  Sales Rep

3. Select all employees that have a last name less than 5. Using inequalities, do this in two different ways using conditionals.

In [37]:
# Strictly less than 5 - FIRST WAY
pd.read_sql(""" 
SELECT * FROM employees WHERE length(lastName) < 5
""", conn)

# OR

# Less than or equal to 4.
pd.read_sql("""
SELECT *, length(lastName) AS name_length
 FROM employees
WHERE name_length <= 4;
""", conn)

,employeeNumber,lastName,firstName,extension,email,officeCode,reportsTo,jobTitle,name_length
0,1143,Bow,Anthony,x5428,abow@classicmodelcars.com,1,1056,Sales Manager (NA),3
1,1501,Bott,Larry,x2311,lbott@classicmodelcars.com,7,1102,Sales Rep,4
2,1619,King,Tom,x103,tking@classicmodelcars.com,6,1088,Sales Rep,4
3,1625,Kato,Yoshimi,x102,ykato@classicmodelcars.com,5,1621,Sales Rep,4

In [14]:
# Strictly less than 5 - SECOND WAY
pd.read_sql( """ 
SELECT * FROM employees WHERE length(lastName) BETWEEN 1 AND 4;
""",conn )

,employeeNumber,lastName,firstName,extension,email,officeCode,reportsTo,jobTitle
0,1143,Bow,Anthony,x5428,abow@classicmodelcars.com,1,1056,Sales Manager (NA)
1,1501,Bott,Larry,x2311,lbott@classicmodelcars.com,7,1102,Sales Rep
2,1619,King,Tom,x103,tking@classicmodelcars.com,6,1088,Sales Rep
3,1625,Kato,Yoshimi,x102,ykato@classicmodelcars.com,5,1621,Sales Rep

In [15]:
# Less than or equal to 4.
pd.read_sql( """ 
SELECT * FROM employees WHERE length(lastName) BETWEEN 1 AND 4;
""",conn )

,employeeNumber,lastName,firstName,extension,email,officeCode,reportsTo,jobTitle
0,1143,Bow,Anthony,x5428,abow@classicmodelcars.com,1,1056,Sales Manager (NA)
1,1501,Bott,Larry,x2311,lbott@classicmodelcars.com,7,1102,Sales Rep
2,1619,King,Tom,x103,tking@classicmodelcars.com,6,1088,Sales Rep
3,1625,Kato,Yoshimi,x102,ykato@classicmodelcars.com,5,1621,Sales Rep

Now let's turn to the orderDetails database.

In [16]:
# Run this code

conn = sqlite3.connect('data.sqlite')
pd.read_sql("""
SELECT *
  FROM orderDetails;
""", conn)

      orderNumber productCode  quantityOrdered  priceEach  orderLineNumber
0           10100    S18_1749               30     136.00                3
1           10100    S18_2248               50      55.09                2
2           10100    S18_4409               22      75.46                4
3           10100    S24_3969               49      35.29                1
4           10101    S18_2325               25     108.06                4
...           ...         ...              ...        ...              ...
2991        10425    S24_2300               49     127.79                9
2992        10425    S24_2840               31      31.82                5
2993        10425    S32_1268               41      83.79               11
2994        10425    S32_2509               11      50.32                6
2995        10425    S50_1392               18      94.92                2

[2996 rows x 5 columns]

4. Round the price as an integer

In [19]:
# Rounding price

pd.read_sql("""
SELECT *, CAST(round(priceEach) AS INTEGER) AS rounded_price_int
FROM orderDetails;
""", conn)

,orderNumber,productCode,quantityOrdered,priceEach,orderLineNumber,rounded_price_int
0,10100,S18_1749,30,136.00,3,136
1,10100,S18_2248,50,55.09,2,55
2,10100,S18_4409,22,75.46,4,75
3,10100,S24_3969,49,35.29,1,35
4,10101,S18_2325,25,108.06,4,108
...,...,...,...,...,...,...
2991,10425,S24_2300,49,127.79,9,128
2992,10425,S24_2840,31,31.82,5,32
2993,10425,S32_1268,41,83.79,11,84
2994,10425,S32_2509,11,50.32,6,50
2995,10425,S50_1392,18,94.92,2,95

Let's look at the orders database.

In [20]:
# Run this code

conn = sqlite3.connect('data.sqlite')
pd.read_sql("""
SELECT *
  FROM orders;
""", conn)

,orderNumber,orderDate,requiredDate,shippedDate,status,comments,customerNumber
0,10100,2003-01-06,2003-01-13,2003-01-10,Shipped,,363
1,10101,2003-01-09,2003-01-18,2003-01-11,Shipped,Check on availability.,128
2,10102,2003-01-10,2003-01-18,2003-01-14,Shipped,,181
3,10103,2003-01-29,2003-02-07,2003-02-02,Shipped,,121
4,10104,2003-01-31,2003-02-09,2003-02-01,Shipped,,141
...,...,...,...,...,...,...,...
321,10421,2005-05-29,2005-06-06,,In Process,Custom shipping instructions were sent to ware...,124
322,10422,2005-05-30,2005-06-11,,In Process,,157
323,10423,2005-05-30,2005-06-05,,In Process,,314
324,10424,2005-05-31,2005-06-08,,In Process,,141
325,10425,2005-05-31,2005-06-07,,In Process,,119

5. Find all orders placed in the year 2005 in the orders database.

In [38]:
# Just 2005


pd.read_sql(
"""
SELECT *, strftime("%Y", orderDate) AS year 
FROM orders 
WHERE year = "2005"; 
""",conn)

,orderNumber,orderDate,requiredDate,shippedDate,status,comments,customerNumber,year
0,10362,2005-01-05,2005-01-16,2005-01-10,Shipped,,161,2005
1,10363,2005-01-06,2005-01-12,2005-01-10,Shipped,,334,2005
2,10364,2005-01-06,2005-01-17,2005-01-09,Shipped,,350,2005
3,10365,2005-01-07,2005-01-18,2005-01-11,Shipped,,320,2005
4,10366,2005-01-10,2005-01-19,2005-01-12,Shipped,,381,2005
...,...,...,...,...,...,...,...,...
59,10421,2005-05-29,2005-06-06,,In Process,Custom shipping instructions were sent to ware...,124,2005
60,10422,2005-05-30,2005-06-11,,In Process,,157,2005
61,10423,2005-05-30,2005-06-05,,In Process,,314,2005
62,10424,2005-05-31,2005-06-08,,In Process,,141,2005
63,10425,2005-05-31,2005-06-07,,In Process,,119,2005

6. Going back to the employees database, use LIKE to find all of those who have sale or sales in their job title.

In [39]:
# Using sales with wildcard

pd.read_sql(""" 
SELECT * 
FROM employees 
WHERE jobTitle LIKE "Sale%";
""", conn)

,employeeNumber,lastName,firstName,extension,email,officeCode,reportsTo,jobTitle
0,1088,Patterson,William,x4871,wpatterson@classicmodelcars.com,6,1056,Sales Manager (APAC)
1,1102,Bondur,Gerard,x5408,gbondur@classicmodelcars.com,4,1056,Sale Manager (EMEA)
2,1143,Bow,Anthony,x5428,abow@classicmodelcars.com,1,1056,Sales Manager (NA)
3,1165,Jennings,Leslie,x3291,ljennings@classicmodelcars.com,1,1143,Sales Rep
4,1166,Thompson,Leslie,x4065,lthompson@classicmodelcars.com,1,1143,Sales Rep
5,1188,Firrelli,Julie,x2173,jfirrelli@classicmodelcars.com,2,1143,Sales Rep
6,1216,Patterson,Steve,x4334,spatterson@classicmodelcars.com,2,1143,Sales Rep
7,1286,Tseng,Foon Yue,x2248,ftseng@classicmodelcars.com,3,1143,Sales Rep
8,1323,Vanauf,George,x4102,gvanauf@classicmodelcars.com,3,1143,Sales Rep
9,1337,Bondur,Loui,x6493,lbondur@classicmodelcars.com,4,1102,Sales Rep
10,1370,Hernandez,Gerard,x2028,ghernande@classicmodelcars.com,4,1102,Sales Rep
11,1401,Castillo,Pamela,x2759,pcastillo@classicmodelcars.com,4,1102,Sales Rep
12,1501,Bott,Larry,x2311,lbott@classicmodelcars.com,7,1102,Sales Rep
13,1504,Jones,Barry,x102,bjones@classicmodelcars.com,7,1102,Sales Rep
14,1611,Fixter,Andy,x101,afixter@classicmodelcars.com,6,1088,Sales Rep
15,1612,Marsh,Peter,x102,pmarsh@classicmodelcars.com,6,1088,Sales Rep
16,1619,King,Tom,x103,tking@classicmodelcars.com,6,1088,Sales Rep
17,1621,Nishi,Mami,x101,mnishi@classicmodelcars.com,5,1056,Sales Rep
18,1625,Kato,Yoshimi,x102,ykato@classicmodelcars.com,5,1621,Sales Rep
19,1702,Gerard,Martin,x2312,mgerard@classicmodelcars.com,4,1102,Sales Rep

7. Now find out how many items are priced at least $200 in the orderDetails database.

In [36]:
# Count each

pd.read_sql( """ 
SELECT * FROM orderDetails WHERE priceEach >= 200
""" ,conn)

    orderNumber productCode  quantityOrdered  priceEach  orderLineNumber
0         10103    S10_1949               26     214.30               11
1         10105    S12_1108               41     205.72               15
2         10126    S10_1949               38     205.73               11
3         10153    S12_1108               20     201.57               11
4         10163    S10_1949               21     212.16                1
5         10174    S10_1949               34     207.87                4
6         10194    S10_1949               42     203.59               11
7         10196    S12_1108               47     203.64                5
8         10206    S10_1949               47     203.59                6
9         10215    S10_1949               35     205.73                3
10        10228    S10_1949               29     214.30                2
11        10280    S10_1949               34     205.73                2
12        10291    S10_1949               37     210.01               11
13        10304    S10_1949               47     201.44                6
14        10312    S10_1949               48     214.30                3
15        10348    S12_1108               48     207.80                8
16        10395    S12_1108               33     205.72                1
17        10411    S10_1949               23     205.73                9
18        10413    S12_1108               36     201.57                2
19        10424    S10_1949               50     201.44                6